version: "3"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_LEVEL=debug
      - RAILS_LOG_TO_STDOUT=true
      - STDOUT_SYNC=true
      - STDERR_SYNC=true
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  redis-data:
